innovation/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings

from .views import CompleteProfile, Home, SignUp, Search, EditProfile, ShowInnovation, crossdomain

admin.autodiscover()

urlpatterns = patterns('',
    url('^$', Home.as_view(), name='home'),
    url('^crossdomain.xml$', crossdomain, name='crossdomain'),
    url('^404$', TemplateView.as_view(template_name='404.html'), name='fourohfour'),
    url('^about$', TemplateView.as_view(template_name='about.html'), name='about'),
    url('^contact$', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url('^accounts/signup/$', SignUp.as_view(), name='account_signup'),
    url('^accounts/signup/profile/$', CompleteProfile.as_view(), name='complete_profile'),

    url(r'^accounts/edit', EditProfile.as_view(), name='edit_profile'),
    url(r'^accounts/', include('allauth.urls')),
    url('^search/?$', Search.as_view(template_name='search.html'), name='search'),

    url('^vote/(?P<target_type>item|comment)/(?P<target_id>\d+)$','innovation.views.vote_up', name='vote'),

    # Examples:
    # url(r'^$', 'innovation.views.home', name='home'),
    # url(r'^innovation/', include('innovation.foo.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # myhacks
    url(r'^myhacks/', include('myhacks.urls', namespace='myhacks')),

    # innovation management
    url(r'^idea/new/$', 'innovation.views.new_innovation', name='new_idea'),
    url(r'^idea/edit/(?P<slug>[^\.]+)/$', 'innovation.views.edit_innovation', name="edit_idea"),
    url(r'^idea/(?P<slug>[^\.]+)/$', ShowInnovation.as_view(), name='idea'),
    # url(r'^idea/(?P<slug>[^\.]+)/$', 'innovation.views.show_innovation', name='idea'),

    # Filebrowser
    (r'^admin/filebrowser/', include('filebrowser.urls')),

    # Tags
    url(r'^tag/(?P<tag>[^\.]+)/$', 'innovation.views.show_tagged_with'),

    # User profiles
    url(r'^user/(?P<username>[^\.]+)/$', 'innovation.views.show_user_profile'),
)

urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    (r'^client_media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

myhacks/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from views import AddView, EditView, HackListView

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='myhacks/home.html'),
                                                                name='home'),
    url(r'^add/$', login_required(AddView.as_view()), name='add'),
    url(r'^(?P<pk>\d+)/edit/$', login_required(EditView.as_view()),
                                                                name='edit'),
    url(r'^all$', HackListView.as_view()),
)

src/innovation/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^accounts/', include('allauth.urls')),

    # Examples:
    # url(r'^$', 'innovation.views.home', name='home'),
    # url(r'^innovation/', include('innovation.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

innovation/models.py
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.db import models
from profiles.models import Profile

from .profile_extensions import InnovationProfile

from filebrowser.fields import FileBrowseField

#plugins needed for comments and tagging

class Item(models.Model):
    """
    Instances of this class represent a specific innovation to be disseminated
    via our portal.  [these must have tags, comments]
    """
    title = models.CharField(max_length = 150, null = False, blank = False)
    slug = models.CharField(max_length = 150, null = False, unique = True)
    created_on = models.DateTimeField(auto_now_add = True)
    created_by = models.ForeignKey(User)
    summary = models.TextField()
    how_used = models.TextField()
    benefits = models.TextField()
    further_information = models.TextField()
    tags = TaggableManager()
    hero_image = FileBrowseField(max_length=200, format='image',
                                                    blank=True, null=True,)

    class Meta:
        ordering = ['-created_on']

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('idea', (), {
        'slug': self.slug
        })

    @models.permalink
    def get_edit_url(self):
        return ('edit_idea', (), {
            'slug' : self.slug,
        })


class Role(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

class Vote(models.Model):
    """
    Users can vote against Items and Comments. Votes can only be positive.
    Votes must record the user Role and ID.
    """
    TARGET_TYPES = (
        ('item', 'Item'),
        ('comment', 'Comment'),
    )
    target_id = models.IntegerField(null = False, blank = False)
    target_type = models.CharField(max_length = 150, null = False,
        blank = False, choices=TARGET_TYPES)
    created_on = models.DateTimeField(auto_now_add = True)
    created_by =  models.ForeignKey(User)

    class Meta:
        ordering = ['-created_on']
        unique_together = ("target_id", "target_type", "created_by")


Profile.register_extensions(InnovationProfile())

innovation/forms.py
from django import forms
from profiles.models import Profile

from models import Item


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('username', 'email', 'first_name', 'last_name', 'affiliation', 'role')


class CompleteProfileForm(ProfileForm):
    class Meta(ProfileForm.Meta):
        exclude = ('username')


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        exclude = ('slug', 'created_by')


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        exclude = ('slug', 'created_by', 'title', 'hero_image')

class HeroImageForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('hero_image',)
        
    hero_image = forms.ImageField(required=False)
    
    def clean_hero_image(self):
        """
        We need to convert the raw image upload (ImageField) in to a path, so
        that when the model is saved, FileBrowser will work. Bit Hacky :/
        """
        data = self.cleaned_data['hero_image']
        from django.core.files.storage import default_storage
        from django.core.files.base import ContentFile
        path = default_storage.save('uploads/%s' % data.name,
                                                    ContentFile(data.read()))
        return path

innovation/views.py
from allauth.account import signals
from allauth.account.forms import SignupForm
from allauth.account.models import EmailAddress
from allauth.account.utils import send_email_confirmation, user_display
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, AnonymousUser
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseNotFound, HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext as _
from django.views.generic import CreateView, TemplateView, UpdateView
from profiles.models import Profile

from .forms import CompleteProfileForm, ItemForm, EditItemForm, HeroImageForm, ProfileForm
from .models import Item, Vote
from .utils import method_decorator


def crossdomain(request):
    r = HttpResponse(mimetype='text/xml')
    r.write("""<?xml version="1.0" ?>
<cross-domain-policy>
<allow-access-from domain="*" />
</cross-domain-policy>""")
    return r

class AuthMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AuthMixin, self).dispatch(request, *args, **kwargs)


class ProfileIncompleteMixin(object):
    def dispatch(self, request, *args, **kwargs):
        if not hasattr(request.user, 'profile') and not isinstance(request.user, AnonymousUser):
            return CompleteProfile.dispatch(CompleteProfile(), request, *args, **kwargs)
        return super(ProfileIncompleteMixin, self).dispatch(request, *args, **kwargs)


class CompleteProfile(CreateView):
    form_class = CompleteProfileForm
    model = Profile
    success_url = '/'
    template_name = 'account/complete_profile.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user_ptr = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_initial(self):
        initial = super(CompleteProfile, self).get_initial()
        initial['email'] = self.request.user.email
        return initial


class SignUp(CreateView):
    form_class = SignupForm
    success_url = reverse_lazy('complete_profile')
    template_name = 'account/signup.html'

    def get_form_kwargs(self):
        kwargs = super(SignUp, self).get_form_kwargs()
        try:
            del kwargs['instance']  # bad allauth
        except KeyError:
            pass
        return kwargs

    def form_valid(self, form):
        """Create and log in the user signing up

        Took this from allauth because extensibility is for chumps.
        """
        self.object = form.save(request=self.request)
        signals.user_signed_up.send(sender=self.object.__class__,
                                    request=self.request,
                                    user=self.object)

        # not is_active: social users are redirected to a template
        # local users are stopped due to form validation checking is_active
        assert self.object.is_active
        if (settings.ACCOUNT_EMAIL_VERIFICATION
            and not EmailAddress.objects.filter(user=self.object,
                                                verified=True).exists()):
            send_email_confirmation(self.object, self.request)

        # HACK: This may not be nice. The proper Django way is to use an
        # authentication backend, but I fail to see any added benefit
        # whereas I do see the downsides (having to bother the integrator
        # to set up authentication backends in settings.py
        if not hasattr(self.object, 'backend'):
            self.object.backend = "django.contrib.auth.backends.ModelBackend"
        signals.user_logged_in.send(sender=self.object.__class__,
                                    request=self.request,
                                    user=self.object)
        login(self.request, self.object)
        msg = _('Successfully signed in as {0}.'.format(user_display(self.object)))
        messages.success(self.request, msg)

        return HttpResponseRedirect(self.get_success_url())


class Search(ProfileIncompleteMixin, TemplateView):
    template_name = 'search.html'

    def get_context_data(self, **kwargs):
        context = super(Search, self).get_context_data(**kwargs)
        context['term'] = term = self.request.GET.get('term', 'FTW')
        innovats = Item.objects.filter(summary__icontains=term)
        context['innovats'] = innovats
        if len(innovats) > 0:
            innovated = True
        else:
            innovated = False
        context['innovated'] = innovated
        return context

class Home(TemplateView):
    template_name = 'home.html'

    def get_context_data(self,**kw):
        context = super(Home, self).get_context_data(**kw)
        try:
            showoff = dict(idea=Item.objects.order_by('?').get())
        except Item.DoesNotExist:
            showoff = {'idea' : Item()}
        except Item.MultipleObjectsReturned:
            showoff = dict(idea=Item.objects.order_by('?')[0])
        votes = Vote.objects.filter(target_id=showoff['idea'].id, target_type='item')
        showoff['votes'] = votes
        context['showoff'] = showoff
        context['recent'] = Item.objects.order_by('created_on')[:10]
        context['top'] = list(Item.objects.order_by('created_on'))[-10:]

        return context

# TODO: CBV & add ProfileIncompleteMixin
@login_required
def new_innovation(request):
    """
    Used for adding a new innovation.
    """
    context = {}
    if request.method == 'POST':
        form = ItemForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            slug = slugify(title)
            created_by = request.user
            summary = form.cleaned_data['summary']
            how_used = form.cleaned_data['how_used']
            benefits = form.cleaned_data['benefits']
            further_information = form.cleaned_data['further_information']
            item = Item.objects.create(title=title, slug=slug,
                created_by=created_by, summary=summary, how_used=how_used,
                benefits=benefits, further_information=further_information)
            tags = [t.lower() for t in form.cleaned_data['tags']]
            item.tags.add(*tags)
            messages.info(request, "Success. You have created a new innovation")
            return HttpResponseRedirect('/idea/%s' % item.slug)
    else:
        form = ItemForm()
    context['form'] = form
    context['post_to'] = '/idea/new/'
    context['title'] = 'Create new innovation'
    return render_to_response('innovation/edit_item.html', context,
        RequestContext(request))

class ShowInnovation(ProfileIncompleteMixin, UpdateView):
    model = Item
    template_name = 'innovation/item.html'
    form_class = HeroImageForm

    def get_context_data(self, **kwargs):
        context = super(ShowInnovation, self).get_context_data(**kwargs)
        context['tags'] = self.object.tags.all()
        return context

# TODO: CBV & add ProfileIncompleteMixin
@login_required
def edit_innovation(request, slug):
    """
    Given an idea identified by a slug will attempt to allow you to edit it.
    """
    item = Item.objects.get(slug=slug)
    if item.created_by != request.user:
        return HttpResponseNotFound()

    context = {}
    if request.method == 'POST':
        form = EditItemForm(request.POST)
        if form.is_valid():
            item.summary = form.cleaned_data['summary']
            item.how_used = form.cleaned_data['how_used']
            item.benefits = form.cleaned_data['benefits']
            item.further_information = form.cleaned_data['further_information']
            item.save()
            tags = [t.lower() for t in form.cleaned_data['tags']]
            item.tags.add(*tags)
            messages.info(request, "Success. You have updated your innovation.")
            return HttpResponseRedirect('/idea/%s' % item.slug)
    else:
        form = EditItemForm(instance=item)
    context['form'] = form
    context['post_to'] = '/idea/edit/%s/' % item.slug
    context['title'] = 'Edit %s' % item.title
    return render_to_response('innovation/edit_item.html', context,
        RequestContext(request))

# TODO: CBV & add ProfileIncompleteMixin
def show_tagged_with(request, tag):
    """
    Given a tag will display a list of all innovations tagged with it.
    """
    tag = tag.lower()
    items = Item.objects.filter(tags__name__in=[tag])
    return render_to_response('innovation/tagged.html',
        {'items': items, 'tag': tag}, RequestContext(request))

# TODO: CBV & add ProfileIncompleteMixin
@login_required
def vote_up(request, target_type, target_id):
    import json
    from .models import Vote

    if Vote.objects.filter(target_type=target_type).\
            filter(created_by=request.user).\
            filter(target_id=target_id).count() == 0:
        Vote.objects.create(target_type=target_type,
                            target_id=target_id,
                            created_by=request.user)

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', "/"))


class EditProfile(AuthMixin, ProfileIncompleteMixin, UpdateView):
    form_class = ProfileForm
    model = Profile
    success_url = reverse_lazy('edit_profile')
    template_name = 'account/edit.html'

    def get_object(self):
        return self.request.user.profile


def show_user_profile(request, username):
    """
    Given a username, displays a page full of information about them.
    """
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return HttpResponseNotFound()

    return render_to_response('innovation/user_profile.html',
        {'user': user}, RequestContext(request))

innovation/templates/about.html
{% extends "base.html" %}
{% load account %}
{% block title %}About{% endblock %}
{% block content %}
<div class="row">
    <div class="span12">
<h1 style="font-size: 72px; line-height: 78px;">&ldquo;If you always do what
you always did, you will always get what you always got.&rdquo;</h1>
<h2>Albert Einstein</h2>
<hr/>
    </div>
</div>
<div class="row">
    <div class="span12">
<h3>NHSonar was built in 48 hours by...<h3>
<a href="http://twitter.com/drcjar"><img src="https://si0.twimg.com/profile_images/1308791386/00134_small_reasonably_small.jpg" class="img-rounded" style="max-width: 64px; margin:8px;"></a>
<a href="http://twitter.com/ghickman"><img src="https://si0.twimg.com/profile_images/1258522839/gravatar_reasonably_small.jpeg" class="img-rounded" style="max-width: 64px; margin:8px;"></a>
<a href="http://twitter.com/londonlime"><img src="https://si0.twimg.com/profile_images/2224516934/game2_reasonably_small.jpg" class="img-rounded" style="max-width: 64px; margin:8px;"></a>
<a href="http://twitter.com/ntoll"><img src="https://si0.twimg.com/profile_images/283774940/100_5406_2_reasonably_small.JPG" class="img-rounded" style="max-width: 64px; margin:8px;"></a>
<a href="http://twitter.com/otfrom"><img src="https://si0.twimg.com/profile_images/1900800660/bld-summer-clj-3-sq_reasonably_small.jpg" class="img-rounded" style="max-width: 64px; margin:8px;"></a>
<a href="http://twitter.com/richardjpope"><img src="https://si0.twimg.com/profile_images/1409940458/grav_bigger_reasonably_small.jpg" class="img-rounded" style="max-width: 64px; margin:8px;"></a>
<a href="http://twitter.com/rossjones"><img src="https://si0.twimg.com/profile_images/2613658204/5j3lqxmuyt984tuxgmoi_reasonably_small.jpeg" class="img-rounded" style="max-width: 64px; margin:8px;"></a>
<a href="http://twitter.com/stephanemassey"><img src="https://si0.twimg.com/profile_images/1575297818/logo_reasonably_small.png" class="img-rounded" style="max-width: 64px; margin:8px;"></a>
<a href="http://twitter.com/symrow"><img src="https://si0.twimg.com/profile_images/2386234934/tns6k105vg7uvp865k61_reasonably_small.jpeg" class="img-rounded" style="max-width: 64px; margin:8px;"></a>
<a href="http://twitter.com/terrycojones"><img src="https://si0.twimg.com/profile_images/2593202437/0n9uxw22rogswzvt8l39_reasonably_small.jpeg" class="img-rounded" style="max-width: 64px; margin:8px;"></a>
<a href="http://twitter.com/thatdavidmiller"><img src="https://si0.twimg.com/profile_images/431557250/profile_reasonably_small.jpg" class="img-rounded" style="max-width: 64px; margin:8px;"></a>
<a href="http://twitter.com/zarino"><img src="https://si0.twimg.com/profile_images/1770997410/IMG_3153_small_reasonably_small.jpg" class="img-rounded" style="max-width: 64px; margin:8px;"></a>
    </div>
</div>
<div class="row">
    <div class="span10 offset1">
<img src="{{ STATIC_URL }}img/laptop.jpg/" class="img-rounded"/>
</div>
</div>
{% endblock content %}

innovation/templates/base.html
{% load url from future %}
{% load innovative_tags %}
{% load i18n %}
{% load avatars %}
{% url 'home' as home_url %}
{% url 'about' as about_url %}
{% url 'contact' as contact_url %}
{# {% url 'myhacks:home' as myhacks_url %} #}


<!doctype html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.ico"/>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
    <link href='http://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'>

    <script type="text/javascript" src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css">
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
    <style type="text/css">
      body {
      padding-top: 60px;
      padding-bottom: 40px;
      }
    </style>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/main.css">
    <title>{% block title %}{% endblock %} | NHSonar</title>

    <script type="text/javascript">
      $(document).ready(function() {
      {% block jqready %}{% endblock %}
      });
    </script>
  </head>
  <body>
    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="{{ home_url }}"><img src="{{STATIC_URL}}img/logowithtagline-trans.png" class="" alt="NHSonar" /></a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="{% active request '' %}"><a href="{{home_url}}">Home</a></li>
              {% if request.user.is_staff %}
                <li class="pull-right"><a href="/admin">Admin</a></li>
              {% endif %}
              <li class="{% active request about_url %}"><a href="{{ about_url }}">About</a></li>
              <li class="{% active request contact_url %}"><a href="{{ contact_url }}">Contact</a></li>
              <li class="dropdown {% active request '/account/*' %}">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  {% if user.is_authenticated %}
                  <li>
                    <a href="{% url 'edit_profile' %}">Profile</a>
                  </li>
                  <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
                  {% else %}
                  <li><a href="{% url 'account_login' %}">Log In</a></li>
                  <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
                  {% endif %}
                </ul>
              </li>
              <li>
                <!-- <button class ="btn btn-primary" type="submit">{% trans "New"%}</button> -->
                <a href="/idea/new/">New Idea</a>
              </li>
              <li>
                <form action="/search" class="navbar-form pull-left">
                  <input type="text" class="span2" name="term" placeholder="Search">
                </form>
              </li>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div id="page" class="container">

      <!-- alerts and messages -->
      <div class="row">
        <div class="span3"></div>
        <div class="span6">
         {% if messages %}
            <div class="alert">
              <button type="button" class="close" data-dismiss="alert">×</button>
              {% for message in messages %}
                {{ message }}
              {% endfor %}
            </div>
         {% endif %}
        </div>
      </div>

        <!-- Main content -->
        {% block content %}

        {% endblock %}
    </div>

        <!-- Footer -->
        <footer>
          <hr />
          <div class="container">


          <div class="row">

            <div class="span6">
              <ul class="nav nav-list">
                <li>
                  <a href="https://github.com/openhealthcare/innovations_r_us">The NHSonar source codes...</a>
                </li>
                <li>
                  <a href="http://nhshackday.com/">...were lovingly crafted on a NHS Hack Day...</a>
                </li>
                <li>
                  <a href="http://openhealthcare.org.uk">...organised by Open Healthcare...</a>
                </li>
              </ul>

            </div>
          </div>

          <p>&copy; NHS - the content on this website is licensed under a <a href="http://creativecommons.org/licenses/by/2.0/uk/">Creative Commons license</a></p>

          </div>

        </footer>

    {% block foot_js %}{% endblock foot_js %}
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-35112560-1']);
      _gaq.push(['_setDomainName', 'openhealthcare.org.uk']);
      _gaq.push(['_trackPageview']);

      (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

</script>
  </body>
</html>

innovation/templates/contact.html
{% extends "base.html" %}
{% load account %}
{% block title %}Contact{% endblock %}
{% block content %}
<h1>Contact</h1>
<div class="container">
  <div class="row-fluid">
    <div class="container span4 offset4">
      <h1>Talk to us!</h1>
      <h1><a href="mailto:carl.reynolds@openhealthcare.co.uk?subject=NHSonar&body=Hello%20NHSonar People,">Send email</a></h1>
    </div>
  </div>
</div>

{% endblock content %}

innovation/templates/home.html
{% extends "base.html" %}
{% load account %}
{% load i18n %}
{% load avatars %}#
{% load social %}

{% block title %}Welcome{% endblock %}
{% block content %}

<h1>Hello there, {{ user.get_full_name }}</h1>

{% include 'innovation/showoff.html' %}
<div class="row">
  <div class="span6">
    <h3>Recent Activity</h3>
    <ul>
    {% for item in recent %}
      <li>
        <a href="/idea/{{item.slug}}">
        {{item.title}}
        </a>
      </li>
    {% endfor %}
    </ul>
  </div>
  <div class="span6">
    <h3>Top Rated</h3>
    {% for item in top %}
      <li>
        <a href="/idea/{{item.slug}}">
        {{item.title}}
        </a>
      </li>
    {% endfor %}
  </div>
</div>





{% endblock content %}

innovation/templates/search.html
{% extends "base.html" %}
{% load account %}
{% load i18n %}
{% block title %}Search{% endblock %}
{% block content %}
<form>
 <input type="text" name="term" value="{{term}}">
 <button class="btn btn-primary" type="submit">{% trans "Already Innovated?" %}</button>
</form>


{% if innovated %}
<h3>Results</h3>
{% for inn in innovats %}
  <p>
   <a href="">{{inn.title}}</a>
  </p>
{% endfor %}
{% else %}
Sorry, what?
{% endif %}

{% endblock content%}